name: Deploy code2ais to AWS EC2
on:
  push:
    branches:
      - main
env:
  EC2_HOST: ${{ secrets.EC2_HOST }}
  SSH_OPTIONS: -o StrictHostKeyChecking=no -o ConnectTimeout=30
jobs:
  startup:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.8.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
      - name: Install Docker and Docker Compose on EC2 if not installed
        run: |
          ssh $SSH_OPTIONS ubuntu@$EC2_HOST '
            if ! command -v docker &> /dev/null; then
              echo "Installing Docker..."
              sudo apt-get update
              ...
            fi
            if ! command -v docker-compose &> /dev/null; then
              echo "Installing Docker Compose..."
              ...
            fi
          '
      - name: Clone repo on EC2 if not exists
        run: |
          ssh $SSH_OPTIONS ubuntu@$EC2_HOST '
            available_space=$(df --output=avail / | tail -1)
            if [ "$available_space" -lt 5000000 ]; then
              echo "Error: Insufficient disk space on / (less than 5GB available)"
              exit 1
            fi
            sudo chown -R ubuntu:ubuntu /home/ubuntu/code2ais
            chmod -R u+rw /home/ubuntu/code2ais
            if [ ! -d "/home/ubuntu/code2ais" ]; then
              ...
            fi
          '
      - name: Clean up SSH key
        if: always()
        run: |
          rm -f ~/.ssh/id_rsa

  frontend-build:
    runs-on: ubuntu-latest
    needs: [startup]
    steps:
      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.8.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
      - name: Build and check Frontend code issues
        run: |
          ssh $SSH_OPTIONS ubuntu@$EC2_HOST '
            cd /home/ubuntu/code2ais/Frontend || { echo "Frontend directory not found"; ls -la /home/ubuntu/code2ais; exit 1; }
            chmod -R u+w /home/ubuntu/code2ais/Frontend
            docker build -t frontend:${{ github.sha }} .
            docker image prune -f
          '

      - name: Clean up SSH key
        if: always()
        run: |
          rm -f ~/.ssh/id_rsa

  backend-build:
    runs-on: ubuntu-latest
    needs: [startup]
    steps:
      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.8.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
      - name: Build and check Backend code issues
        run: |
          ssh $SSH_OPTIONS ubuntu@$EC2_HOST '
            cd /home/ubuntu/code2ais/Backend || { echo "Backend directory not found"; ls -la /home/ubuntu/code2ais; exit 1; }
            chmod -R u+w /home/ubuntu/code2ais/Backend
            docker build -t backend:${{ github.sha }} .
            docker image prune -f
          '
      - name: Clean up SSH key
        if: always()
        run: |
          rm -f ~/.ssh/id_rsa

  deploy:
    runs-on: ubuntu-latest
    needs: [frontend-build,backend-build]
    steps:
      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.8.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
      - name: Deploy frontend, backend ...
        run: |
          ssh $SSH_OPTIONS ubuntu@$EC2_HOST '
            cd /home/ubuntu/code2ais
            if [ ! -f docker-compose.yml ]; then
              echo "Error: docker-compose.yml not found"
              exit 1
            fi
            docker-compose -f docker-compose.yml up -d --build --force-recreate 2>&1 | tee /home/ubuntu/code2ais/docker-compose.log
            docker system prune -a -f
            docker builder prune -f
            echo "Checking running containers..."
            docker ps -a
          '